<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // KPR Products
            [
                'category_id' => 1,
                'name' => 'KPR BCA Konvensional',
                'slug' => 'kpr-bca-konvensional',
                'description' => 'KPR dengan bunga kompetitif dari BCA untuk pembelian rumah baru atau second',
                'interest_rate_min' => 8.50,
                'interest_rate_max' => 10.50,
                'tenor_min' => 12,
                'tenor_max' => 240,
                'amount_min' => 50000000,
                'amount_max' => 5000000000,
                'requirements' => 'KTP, NPWP, Slip Gaji, Rekening Koran 3 bulan terakhir',
                'benefits' => 'Bunga kompetitif, Tenor panjang hingga 20 tahun, Proses cepat',
                'provider' => 'Bank BCA',
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'KPR Mandiri Griya Utama',
                'slug' => 'kpr-mandiri-griya-utama',
                'description' => 'Program KPR dari Bank Mandiri dengan berbagai kemudahan',
                'interest_rate_min' => 8.25,
                'interest_rate_max' => 10.25,
                'tenor_min' => 12,
                'tenor_max' => 300,
                'amount_min' => 50000000,
                'amount_max' => 7500000000,
                'requirements' => 'KTP, NPWP, Slip Gaji, Surat Keterangan Kerja',
                'benefits' => 'DP mulai 0%, Proses approval cepat, Biaya provisi kompetitif',
                'provider' => 'Bank Mandiri',
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'KPR BRI Griya Utama',
                'slug' => 'kpr-bri-griya-utama',
                'description' => 'Solusi kepemilikan rumah impian dengan KPR BRI',
                'interest_rate_min' => 7.99,
                'interest_rate_max' => 9.99,
                'tenor_min' => 12,
                'tenor_max' => 240,
                'amount_min' => 50000000,
                'amount_max' => 5000000000,
                'requirements' => 'KTP, NPWP, Slip Gaji 3 bulan, Surat Keterangan Kerja',
                'benefits' => 'Bunga rendah, Subsidi pemerintah tersedia, Proses mudah',
                'provider' => 'Bank BRI',
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'KPR BTN Platinum',
                'slug' => 'kpr-btn-platinum',
                'description' => 'KPR khusus untuk properti premium dari Bank BTN',
                'interest_rate_min' => 8.75,
                'interest_rate_max' => 11.00,
                'tenor_min' => 12,
                'tenor_max' => 240,
                'amount_min' => 100000000,
                'amount_max' => 10000000000,
                'requirements' => 'KTP, NPWP, Slip Gaji, Bukti Kepemilikan Aset',
                'benefits' => 'Untuk properti premium, Limit tinggi, Layanan priority',
                'provider' => 'Bank BTN',
                'is_active' => true,
            ],
            
            // KTA Products
            [
                'category_id' => 2,
                'name' => 'KTA BCA',
                'slug' => 'kta-bca',
                'description' => 'Kredit Tanpa Agunan untuk berbagai kebutuhan dari BCA',
                'interest_rate_min' => 12.50,
                'interest_rate_max' => 16.50,
                'tenor_min' => 6,
                'tenor_max' => 60,
                'amount_min' => 10000000,
                'amount_max' => 200000000,
                'requirements' => 'KTP, NPWP, Slip Gaji, Rekening BCA minimal 6 bulan',
                'benefits' => 'Tanpa agunan, Proses cepat 2-3 hari, Pencairan langsung ke rekening',
                'provider' => 'Bank BCA',
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Mandiri KTA',
                'slug' => 'mandiri-kta',
                'description' => 'KTA dari Bank Mandiri dengan limit hingga 300 juta',
                'interest_rate_min' => 12.00,
                'interest_rate_max' => 15.50,
                'tenor_min' => 6,
                'tenor_max' => 48,
                'amount_min' => 10000000,
                'amount_max' => 300000000,
                'requirements' => 'KTP, NPWP, Slip Gaji 3 bulan terakhir',
                'benefits' => 'Limit besar, Bunga kompetitif, Tanpa biaya pelunasan',
                'provider' => 'Bank Mandiri',
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'CIMB Niaga Xtra Dana',
                'slug' => 'cimb-niaga-xtra-dana',
                'description' => 'Pinjaman tunai tanpa agunan dari CIMB Niaga',
                'interest_rate_min' => 11.50,
                'interest_rate_max' => 14.99,
                'tenor_min' => 12,
                'tenor_max' => 60,
                'amount_min' => 10000000,
                'amount_max' => 200000000,
                'requirements' => 'KTP, NPWP, Slip Gaji, Rekening CIMB Niaga',
                'benefits' => 'Approval cepat, Bunga rendah, Tanpa jaminan',
                'provider' => 'CIMB Niaga',
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Permata KTA Express',
                'slug' => 'permata-kta-express',
                'description' => 'KTA kilat dari Bank Permata dengan proses 24 jam',
                'interest_rate_min' => 13.00,
                'interest_rate_max' => 17.00,
                'tenor_min' => 6,
                'tenor_max' => 36,
                'amount_min' => 5000000,
                'amount_max' => 150000000,
                'requirements' => 'KTP, Slip Gaji, Rekening Bank',
                'benefits' => 'Proses super cepat, Tanpa agunan, Pencairan 24 jam',
                'provider' => 'Bank Permata',
                'is_active' => true,
            ],
            
            // Credit Card Products
            [
                'category_id' => 3,
                'name' => 'BCA Card Platinum',
                'slug' => 'bca-card-platinum',
                'description' => 'Kartu kredit premium dengan berbagai benefit eksklusif',
                'interest_rate_min' => 2.25,
                'interest_rate_max' => 2.95,
                'tenor_min' => 1,
                'tenor_max' => 36,
                'amount_min' => 5000000,
                'amount_max' => 100000000,
                'requirements' => 'KTP, NPWP, Slip Gaji minimal Rp 10 juta',
                'benefits' => 'Airport lounge access, Reward points, Cicilan 0%',
                'provider' => 'Bank BCA',
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Mandiri World Elite Card',
                'slug' => 'mandiri-world-elite-card',
                'description' => 'Kartu kredit elite dengan limit tinggi dan benefits premium',
                'interest_rate_min' => 2.50,
                'interest_rate_max' => 3.00,
                'tenor_min' => 1,
                'tenor_max' => 36,
                'amount_min' => 10000000,
                'amount_max' => 200000000,
                'requirements' => 'KTP, NPWP, Penghasilan minimal Rp 15 juta/bulan',
                'benefits' => 'Concierge service, Travel insurance, Cashback program',
                'provider' => 'Bank Mandiri',
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'CIMB Niaga Travel Card',
                'slug' => 'cimb-niaga-travel-card',
                'description' => 'Kartu kredit khusus untuk traveler dengan berbagai benefit',
                'interest_rate_min' => 2.00,
                'interest_rate_max' => 2.75,
                'tenor_min' => 1,
                'tenor_max' => 24,
                'amount_min' => 5000000,
                'amount_max' => 80000000,
                'requirements' => 'KTP, Slip Gaji minimal Rp 5 juta',
                'benefits' => 'Miles reward, Travel insurance, Airport pickup',
                'provider' => 'CIMB Niaga',
                'is_active' => true,
            ],
            
            // Vehicle Credit Products
            [
                'category_id' => 4,
                'name' => 'BCA Finance Kredit Mobil',
                'slug' => 'bca-finance-kredit-mobil',
                'description' => 'Pembiayaan mobil baru dan bekas dengan bunga kompetitif',
                'interest_rate_min' => 6.50,
                'interest_rate_max' => 9.50,
                'tenor_min' => 12,
                'tenor_max' => 60,
                'amount_min' => 50000000,
                'amount_max' => 2000000000,
                'requirements' => 'KTP, SIM, STNK, Slip Gaji',
                'benefits' => 'DP mulai 20%, Asuransi lengkap, Proses cepat',
                'provider' => 'BCA Finance',
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Mandiri Tunas Finance Motor',
                'slug' => 'mandiri-tunas-finance-motor',
                'description' => 'Kredit motor dengan DP rendah dan tenor fleksibel',
                'interest_rate_min' => 8.00,
                'interest_rate_max' => 12.00,
                'tenor_min' => 12,
                'tenor_max' => 36,
                'amount_min' => 10000000,
                'amount_max' => 100000000,
                'requirements' => 'KTP, KK, Slip Gaji atau Surat Usaha',
                'benefits' => 'DP ringan, Proses mudah, Angsuran terjangkau',
                'provider' => 'Mandiri Tunas Finance',
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Adira Finance Mobil Bekas',
                'slug' => 'adira-finance-mobil-bekas',
                'description' => 'Solusi kredit untuk pembelian mobil bekas berkualitas',
                'interest_rate_min' => 7.50,
                'interest_rate_max' => 11.00,
                'tenor_min' => 12,
                'tenor_max' => 48,
                'amount_min' => 30000000,
                'amount_max' => 500000000,
                'requirements' => 'KTP, KK, Bukti Penghasilan, BPKB Asli',
                'benefits' => 'Mobil bekas berkualitas, Survey cepat, DP fleksibel',
                'provider' => 'Adira Finance',
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'FIF Kredit Motor Syariah',
                'slug' => 'fif-kredit-motor-syariah',
                'description' => 'Pembiayaan motor dengan prinsip syariah',
                'interest_rate_min' => 9.00,
                'interest_rate_max' => 13.00,
                'tenor_min' => 12,
                'tenor_max' => 36,
                'amount_min' => 10000000,
                'amount_max' => 80000000,
                'requirements' => 'KTP, KK, Bukti Penghasilan',
                'benefits' => 'Sesuai prinsip syariah, Tanpa bunga, Margin kompetitif',
                'provider' => 'Federal International Finance',
                'is_active' => true,
            ],
            
            // Multiguna Products
            [
                'category_id' => 5,
                'name' => 'BRI Multiguna',
                'slug' => 'bri-multiguna',
                'description' => 'Kredit serbaguna dengan agunan properti atau kendaraan',
                'interest_rate_min' => 10.00,
                'interest_rate_max' => 14.00,
                'tenor_min' => 12,
                'tenor_max' => 120,
                'amount_min' => 20000000,
                'amount_max' => 2000000000,
                'requirements' => 'KTP, NPWP, Slip Gaji, Sertifikat/BPKB',
                'benefits' => 'Limit besar, Tenor panjang, Berbagai keperluan',
                'provider' => 'Bank BRI',
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Danamon Kredit Dana Tunai',
                'slug' => 'danamon-kredit-dana-tunai',
                'description' => 'Kredit tunai dengan agunan untuk berbagai kebutuhan',
                'interest_rate_min' => 11.00,
                'interest_rate_max' => 15.00,
                'tenor_min' => 12,
                'tenor_max' => 84,
                'amount_min' => 30000000,
                'amount_max' => 1500000000,
                'requirements' => 'KTP, Kartu Keluarga, Slip Gaji, Agunan',
                'benefits' => 'Proses cepat, Pencairan hingga 80% nilai agunan',
                'provider' => 'Bank Danamon',
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Mega Credit Plus',
                'slug' => 'mega-credit-plus',
                'description' => 'Kredit multiguna dari Bank Mega dengan limit tinggi',
                'interest_rate_min' => 10.50,
                'interest_rate_max' => 14.50,
                'tenor_min' => 12,
                'tenor_max' => 96,
                'amount_min' => 25000000,
                'amount_max' => 1000000000,
                'requirements' => 'KTP, NPWP, Slip Gaji, Dokumen Agunan',
                'benefits' => 'Penggunaan fleksibel, Limit tinggi, Proses mudah',
                'provider' => 'Bank Mega',
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Permata Kredit Serbaguna',
                'slug' => 'permata-kredit-serbaguna',
                'description' => 'Solusi kredit untuk berbagai kebutuhan dengan agunan',
                'interest_rate_min' => 11.50,
                'interest_rate_max' => 16.00,
                'tenor_min' => 12,
                'tenor_max' => 72,
                'amount_min' => 20000000,
                'amount_max' => 800000000,
                'requirements' => 'KTP, Slip Gaji, Dokumen Agunan',
                'benefits' => 'Untuk berbagai kebutuhan, Bunga kompetitif, Pelayanan cepat',
                'provider' => 'Bank Permata',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
